#include "editor/McpServer.h"
#include "core/FileSystem.h"
#include "core/Image.h"
#include "core/Log.h"
#include <algorithm>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <iostream>
#include <random>
#include <sstream>
#include <stdexcept>
#ifdef _WIN32
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <winsock2.h>
#include <ws2tcpip.h>   // ws2_32 is linked by CMakeLists.txt
using socklen_t = int;
#else
#include <arpa/inet.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <sys/socket.h>
#include <unistd.h>
#endif

namespace df {
using json = nlohmann::json;
namespace fs = std::filesystem;
namespace {
constexpr const char* kProtocols[] = {"2025-11-25", "2025-06-18", "2025-03-26", "2024-11-05"};   // newest first
constexpr int kInvalidRequest = -32600, kMethodNotFound = -32601, kInvalidParams = -32602, kInternalError = -32603,
              kResourceNotFound = -32002;
constexpr const char* kLogLevels[] = {"debug", "info", "notice", "warning", "error", "critical", "alert", "emergency"};

json rpcError(const json& id, int code, const std::string& msg, json data = nullptr) {
    json e = {{"code", code}, {"message", msg}};
    if (!data.is_null()) e["data"] = std::move(data);
    return {{"jsonrpc", "2.0"}, {"id", id}, {"error", e}};
}
json rpcResult(const json& id, json result) { return {{"jsonrpc", "2.0"}, {"id", id}, {"result", std::move(result)}}; }
// never throws on bad UTF-8 (file names, log lines)
std::string dumpJson(const json& j, int indent = -1) { return j.dump(indent, ' ', false, json::error_handler_t::replace); }

// a JSON-RPC error answer, thrown while handling a request
struct RpcError : std::runtime_error {
    int code;
    json data;
    RpcError(int code, const std::string& msg, json data = nullptr) : std::runtime_error(msg), code(code), data(std::move(data)) {}
};
struct ScopeExit {
    std::function<void()> fn;
    ~ScopeExit() { fn(); }
};

// ------------------------------------------------------------------------------------- resources
struct DocResource { const char *name, *file, *title, *description; };
constexpr DocResource kDocs[] = {
    {"agent-workflow", "AGENT_WORKFLOW.md", "Agent workflow",
     "How to build levels with the tools: read first, batches, captures, walk tests, the enforced rules."},
    {"map-format", "MAP_FORMAT.md", "Map format", "Every section and field of map.json, the terrain files and the content library."},
    {"tools", "TOOLS.md", "Tool reference", "Every tool with its arguments (generated by dayfall --list-tools)."},
    {"porting", "PORTING.md", "Porting guide", "Porting the Unreal level and the Blender worlds into DAYFALL maps."},
};
// world_get's sections; any other top-level key of the document works too
constexpr const char* kSections[] = {"objects", "scatter", "paths", "entities", "lights", "environment", "player", "player_start",
                                     "cameras", "routes", "terrain", "materials", "meshes", "hud"};

std::string imageMime(const fs::path& p) {
    std::string e = p.extension().string();
    for (auto& c : e) c = (char)tolower((unsigned char)c);
    return e == ".jpg" || e == ".jpeg" ? "image/jpeg" : e == ".png" ? "image/png" : "";
}

struct CaptureFile { fs::path path; fs::file_time_type time; uintmax_t size; };
std::vector<CaptureFile> newestCaptures(const fs::path& mapDir, size_t max) {
    std::vector<CaptureFile> out;
    if (mapDir.empty()) return out;
    try {
        std::error_code ec;
        for (const auto& e : fs::directory_iterator(mapDir / "captures", ec))
            if (e.is_regular_file() && !imageMime(e.path()).empty()) out.push_back({e.path(), e.last_write_time(), e.file_size()});
    } catch (const fs::filesystem_error&) {}
    std::sort(out.begin(), out.end(), [](auto& a, auto& b) { return a.time > b.time; });
    if (out.size() > max) out.resize(max);
    return out;
}

// ------------------------------------------------------------------------------------- prompts
// The agent workflow (docs/AGENT_WORKFLOW.md) as ready-made requests. Arguments arrive as strings.
struct PromptArg { const char *name, *description; bool required; };
struct Prompt {
    const char *name, *title, *description;
    std::vector<PromptArg> args;
    std::function<std::string(const json&)> text;
};
std::string arg(const json& a, const char* k) {
    if (!a.contains(k) || a[k].is_null()) return "";
    return a[k].is_string() ? a[k].get<std::string>() : a[k].dump();
}
const std::vector<Prompt>& prompts() {
    static const std::vector<Prompt> p = {
        {"build_level", "Build a level", "Build a playable level from a description, following the DAYFALL agent workflow.",
         {{"description", "What to build: terrain, paths, buildings, collectibles, mood", true},
          {"map", "Create it as a new map in this folder (e.g. maps/valley_town); empty: change the open map", false}},
         [](const json& a) {
             std::string map = arg(a, "map");
             return "Build this level in the live DAYFALL editor: " + arg(a, "description") + "\n" +
                    (map.empty() ? "" : "Create it as a new map with map_new {\"dir\": \"" + map + "\"}.\n") +
                    "\nFollow the agent workflow (resource dayfall://docs/agent-workflow):\n"
"1. Read first: project_info, then world_get, catalog and terrain_info. Change nothing until you know the map. "
                    "When the human points at something (\"this\", \"here\"), editor_state says what they selected.\n"
                    "2. One theme per batch: batch_begin {title} -> a few related edits -> capture -> look at the images -> fix -> "
                    "batch_end. Never change terrain, lighting and the character in one batch (the engine refuses).\n"
"3. Order: terrain (terrain_generate, terrain_sculpt, terrain_paint; water_set for lakes and rivers) -> paths "
                    "(path_set) -> name the places (area_set) -> blockout with primitives (find_space for level sites, object_add "
                    "with place {on / next_to / relative_to} instead of guessed coordinates, place_along_path) -> gameplay "
                    "(entity_add; player_set start for the player start) -> route_set and walk_test until passed is true, play_sim "
                    "for jumps -> art (catalog meshes, asset_import, object_update, scatter_set; prefab_save a dressed group once "
                    "and prefab_place it at each site) -> lighting (environment_set, light_set).\n"
                    "4. A successful tool call does not mean the level is right. In every capture look for floating or buried "
"objects, gaps, scale against the 1.8 m mannequin, broken paths, empty or cluttered areas and exposure. Before "
                    "batch_end run world_check (it finds floating, buried and duplicate objects, objects on paths, entities inside "
                    "walls) and fix what it reports; world_diff lists the batch's changes for its notes.\n\n"
                    "Finish with a short report: what you built, the walk_test result, and what the final captures show.";
         }},
        {"review_level", "Review the level", "Capture and walk-test the open map and report its problems, without changing it.",
         {{"route", "The route to walk-test; empty: every route in project_info", false},
          {"focus", "What to look at most closely (e.g. the town, the jumps, lighting)", false}},
         [](const json& a) {
             std::string route = arg(a, "route"), focus = arg(a, "focus");
             return "Review the open DAYFALL level without changing it" + (focus.empty() ? std::string(".") : ", focusing on: " + focus + ".") +
                    "\n\n1. project_info, then world_get for the sections you need.\n"
                    "2. capture the overview, player and top_down views, then every saved camera (at most 6 views per call). "
                    "Look at each image: floating or buried objects, gaps, scale against the 1.8 m mannequin, paths, lighting.\n"
                    "3. walk_test " +
                    (route.empty() ? std::string("every route listed by project_info (with no routes: walk_test {path_id} along the main path)")
                                   : "the route " + route) +
                    ", and look at the capture of each problem spot.\n"
"4. play_sim a short run from the player start (forward 3 s, a jump, turn 90 degrees, forward 2 s; captures each).\n"
                    "5. world_check {min_severity: info} and include its errors and warnings.\n\n"
                    "Report what each capture shows, every walk_test problem with its position, and a prioritised list of fixes. "
                    "Do not edit the map.";
         }},
        {"refine_area", "Refine an area", "Improve one area of the open map in small, verified batches.",
         {{"area", "Where: a place and position, e.g. \"the town square around [120, 340]\"", true},
          {"goal", "What should change, e.g. \"more lived-in: market props, lanterns, grass\"", true}},
         [](const json& a) {
             return "Refine an area of the open DAYFALL map.\nArea: " + arg(a, "area") + "\nGoal: " + arg(a, "goal") +
"\n\n1. Read the area: name it with area_set (then every area argument takes the name), world_get with near "
                    "{position, radius_m}, ground_query for the ground, world_check {area}, and capture an orbit view of it (keep "
                    "the view to repeat it).\n"
                    "2. Plan small batches with one theme each (layout, foliage, lighting, gameplay); terrain, lighting and "
                    "character changes never share a batch.\n"
"3. Each batch: batch_begin -> edits -> capture the same orbit view -> compare with the one before -> world_check "
                    "{area} -> fix -> batch_end.\n"
                    "4. If a route crosses the area, walk_test it at the end.\n\n"
                    "Report what changed, with the before and after captures.";
         }},
        {"test_route", "Test a route", "Walk-test a route with the default mannequin, fix every problem, and test the jumps.",
         {{"route", "A route name from project_info, or where it should go (e.g. \"from the player start to the goal\")", true}},
         [](const json& a) {
             return "Test this route of the open DAYFALL level with the default mannequin: " + arg(a, "route") +
                    "\n\n1. If it is not a route listed by project_info, define it with route_set (waypoints along the walkable "
                    "way, or path_id).\n"
                    "2. walk_test it. For every stuck, fall, steep, water or timeout event, look at its capture, fix the cause in a "
                    "small batch (batch_begin -> fix -> capture -> batch_end) and walk_test again until passed is true.\n"
                    "3. Test the jumps, ledges and stairs on the way with play_sim (move, run, jump steps; captures each).\n\n"
                    "Report the final walk_test result and every fix you made.";
         }},
    };
    return p;
}
}  // namespace

bool McpServer::supportsProtocol(const std::string& v) {
    return std::find(std::begin(kProtocols), std::end(kProtocols), v) != std::end(kProtocols);
}
const char* McpServer::latestProtocol() { return kProtocols[0]; }

fs::path McpServer::mapDir() {
    fs::path d;
    queue_.post([&] { d = editor_.world.dir; }).wait();
    return d;
}

json McpServer::toolList() const {
    json tools = json::array();
    for (const Tool& t : editor_.tools()) {
        bool readOnly = t.category == ToolCategory::Read;
        json annotations = {{"readOnlyHint", readOnly}, {"destructiveHint", t.name == "delete" || t.name == "terrain_generate"},
                            {"idempotentHint", readOnly}, {"openWorldHint", false}};
        json schema = t.schema;
        if (!schema.contains("properties")) schema["properties"] = json::object();
        tools.push_back({{"name", t.name}, {"title", t.title.empty() ? toolTitle(t.name) : t.title}, {"description", t.description},
                         {"inputSchema", schema}, {"annotations", annotations}});
    }
    return tools;
}

json McpServer::resourceList() {
    json out = json::array();
    for (const DocResource& d : kDocs) {
        std::error_code ec;
        fs::path p = editor_.options.docsDir / d.file;
        if (!fs::is_regular_file(p, ec)) continue;
        json r = {{"uri", std::string("dayfall://docs/") + d.name}, {"name", d.name}, {"title", d.title}, {"description", d.description},
                  {"mimeType", "text/markdown"}};
        if (auto size = fs::file_size(p, ec); !ec) r["size"] = size;
        out.push_back(r);
    }
    out.push_back({{"uri", "dayfall://map/document"}, {"name", "map-document"}, {"title", "Map document (live)"},
                   {"description", "The open map's map.json as it is in the editor now, unsaved edits included."},
                   {"mimeType", "application/json"}});
    for (const CaptureFile& c : newestCaptures(mapDir(), 20)) {
        std::string file = c.path.filename().string();
        json r = {{"uri", "dayfall://captures/" + file}, {"name", file}, {"title", "Capture " + c.path.stem().string()},
                  {"description", "A capture saved under <map>/captures/ (newest first)."}, {"mimeType", imageMime(c.path)}, {"size", c.size}};
        auto sys = std::chrono::floor<std::chrono::seconds>(std::chrono::file_clock::to_sys(c.time));
        r["annotations"] = {{"audience", {"user", "assistant"}}, {"lastModified", std::format("{:%FT%TZ}", sys)}};
        out.push_back(r);
    }
    return out;
}

json McpServer::resourceTemplates() const {
    std::string sections;
    for (const char* s : kSections) sections += (sections.empty() ? "" : ", ") + std::string(s);
    return json::array({{{"uriTemplate", "dayfall://map/section/{section}"}, {"name", "map-section"}, {"title", "Map document section (live)"},
                         {"description", "One section of the open map's document: " + sections + "."}, {"mimeType", "application/json"}},
                        {{"uriTemplate", "dayfall://captures/{file}"}, {"name", "capture"}, {"title", "Capture image"},
                         {"description", "An image saved under <map>/captures/ by capture, walk_test or play_sim (resources/list shows the newest 20)."}}});
}

json McpServer::readResource(const std::string& uri) {
    auto notFound = [&] { return RpcError(kResourceNotFound, "Resource not found: " + uri, {{"uri", uri}}); };
    auto text = [&](const char* mime, std::string body) {
        return json{{"contents", json::array({{{"uri", uri}, {"mimeType", mime}, {"text", std::move(body)}}})}};
    };
    const std::string docs = "dayfall://docs/", section = "dayfall://map/section/", captures = "dayfall://captures/";
    if (uri.rfind(docs, 0) == 0) {
        for (const DocResource& d : kDocs) {
            std::error_code ec;
            fs::path p = editor_.options.docsDir / d.file;
            if (uri.substr(docs.size()) == d.name && fs::is_regular_file(p, ec)) return text("text/markdown", readText(p));
        }
        throw notFound();
    }
    if (uri == "dayfall://map/document" || uri.rfind(section, 0) == 0) {
        bool whole = uri == "dayfall://map/document";
        std::string name = whole ? "" : uri.substr(section.size());
        bool known = std::find(std::begin(kSections), std::end(kSections), name) != std::end(kSections);
        json value;
        bool found = false;
        queue_.post([&] {   // the document belongs to the main thread
            const json& d = editor_.world.doc;
            found = whole || d.contains(name);
            if (found) value = whole ? d : d.at(name);
        }).wait();
        if (!found && !known) throw notFound();
        return text("application/json", dumpJson(value, 1));   // a known section the map does not have yet: null
    }
    if (uri.rfind(captures, 0) == 0) {
        std::string file = uri.substr(captures.size());
        bool safe = !file.empty() && file.find("..") == std::string::npos &&
                    file.find_first_not_of("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789._-") == std::string::npos;
        fs::path dir = safe ? mapDir() : fs::path();
        fs::path p = dir / "captures" / file;
        std::error_code ec;
        if (!safe || dir.empty() || imageMime(p).empty() || !fs::is_regular_file(p, ec)) throw notFound();
        return {{"contents", json::array({{{"uri", uri}, {"mimeType", imageMime(p)}, {"blob", base64(readBinary(p))}}})}};
    }
    throw notFound();
}

json McpServer::promptList() const {
    json out = json::array();
    for (const Prompt& p : prompts()) {
        json args = json::array();
        for (const PromptArg& a : p.args) args.push_back({{"name", a.name}, {"description", a.description}, {"required", a.required}});
        out.push_back({{"name", p.name}, {"title", p.title}, {"description", p.description}, {"arguments", args}});
    }
    return out;
}

json McpServer::getPrompt(const std::string& name, const json& args) const {
    for (const Prompt& p : prompts()) {
        if (name != p.name) continue;
        for (const PromptArg& a : p.args)
            if (a.required && arg(args, a.name).empty()) throw RpcError(kInvalidParams, std::format("prompt {} needs the argument '{}'", name, a.name));
        json msg = {{"role", "user"}, {"content", {{"type", "text"}, {"text", p.text(args)}}}};
        return {{"description", p.description}, {"messages", json::array({msg})}};
    }
    throw RpcError(kInvalidParams, "unknown prompt: " + name);
}

void McpServer::cancel(const McpSession& s, const json& requestId) {
    std::string key = s.id + "|" + requestId.dump();
    bool known = false, running = false;
    {
        std::lock_guard lock(callsMutex_);
        auto it = inFlight_.find(key);
        if (it == inFlight_.end()) {   // not seen yet (stdio hands requests to worker threads) or already answered
            cancelledEarly_.push_back(key);
            if (cancelledEarly_.size() > 64) cancelledEarly_.pop_front();
        } else {
            known = true;
            it->second->cancelled = true;
            running = running_ == it->second;
            if (running) editor_.cancelRequested = true;   // the tool stops at its next progress report
        }
    }
    if (known) logInfo("MCP request {} cancelled{}", requestId.dump(), running ? " while running" : " before it ran");
}

json McpServer::callTool(const json& id, const json& params, McpSession& s, const McpNotify& notify, bool& noResponse) {
    if (!params.contains("name") || !params["name"].is_string()) throw RpcError(kInvalidParams, "tools/call needs the tool name");
    std::string name = params["name"].get<std::string>();
    bool known = false;
    for (const Tool& t : editor_.tools()) known |= t.name == name;
    if (!known) throw RpcError(kInvalidParams, "unknown tool: " + name);
    json args = params.contains("arguments") && !params["arguments"].is_null() ? params["arguments"] : json::object();
    if (!args.is_object()) throw RpcError(kInvalidParams, "tools/call arguments must be an object");
    json token = params.contains("_meta") && params["_meta"].is_object() ? params["_meta"].value("progressToken", json()) : json();

    auto call = std::make_shared<Call>();
    std::string key = s.id + "|" + id.dump();
    {
        std::lock_guard lock(callsMutex_);
        inFlight_[key] = call;
        if (auto it = std::find(cancelledEarly_.begin(), cancelledEarly_.end(), key); it != cancelledEarly_.end()) {
            call->cancelled = true;
            cancelledEarly_.erase(it);
        }
    }
    ToolResult res;
    ++calls;
    auto t0 = std::chrono::steady_clock::now();
    queue_.post([&] {
        {
            std::lock_guard lock(callsMutex_);
            if (call->cancelled) { res = ToolResult::fail("cancelled"); return; }   // cancelled while it waited for the main thread
            running_ = call;
            editor_.cancelRequested = false;
        }
        ScopeExit done{[this] {   // before the response: no progress after it
            editor_.progress = nullptr;
            std::lock_guard lock(callsMutex_);
            running_.reset();
            editor_.cancelRequested = false;
        }};
        if (!token.is_null() && notify) {
            // progress must increase; at most ~10 notifications a second, none once the client cancelled
            editor_.progress = [&, last = -1.0, sent = std::chrono::steady_clock::time_point()](double p, double total, const std::string& msg) mutable {
                auto now = std::chrono::steady_clock::now();
                if (call->cancelled || p <= last || (last >= 0 && now - sent < std::chrono::milliseconds(100))) return;
                last = p;
                sent = now;
                json n = {{"progressToken", token}, {"progress", p}, {"message", msg}};
                if (total > 0) n["total"] = total;
                notify({{"jsonrpc", "2.0"}, {"method", "notifications/progress"}, {"params", n}});
            };
        }
        res = editor_.call(name, args);
    }).wait();
    bool cancelled = call->cancelled;
    {
        std::lock_guard lock(callsMutex_);
        inFlight_.erase(key);
    }
    double ms = std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count();
    logInfo("tool {} {} in {:.0f} ms", name, cancelled ? "cancelled" : res.error ? "FAILED" : "ok", ms);
    if (cancelled && s.stdio) {   // the client gave up on it: no response (HTTP still answers its POST)
        noResponse = true;
        return json();
    }
    json content = json::array();
    content.push_back({{"type", "text"}, {"text", dumpJson(res.data, 1)}});
    for (auto& img : res.images) content.push_back({{"type", "image"}, {"data", img.base64}, {"mimeType", img.mime}});
    json out = {{"content", content}, {"isError", res.error}};
    if (s.protocol() >= "2025-06-18") out["structuredContent"] = res.data.is_object() ? res.data : json{{"result", res.data}};
    return out;
}

json McpServer::handleRequest(const std::string& method, const json& id, const json& params, McpSession& s, const McpNotify& notify,
                              bool& noResponse) {
    if (method == "initialize") {
        std::string want = params.contains("protocolVersion") && params["protocolVersion"].is_string() ? params["protocolVersion"].get<std::string>() : "";
        std::string use = supportsProtocol(want) ? want : latestProtocol();
        s.setProtocol(use);
        json client = params.value("clientInfo", json::object());
        logInfo("MCP client connected: {} {} (protocol {}{})", client.value("name", "?"), client.value("version", ""), use,
                s.id.empty() || s.stdio ? "" : ", session " + s.id.substr(0, 8));
        json caps = {{"tools", {{"listChanged", false}}}, {"resources", {{"subscribe", false}, {"listChanged", false}}},
                     {"prompts", {{"listChanged", false}}}};
        if (s.stdio) caps["logging"] = json::object();   // engine warnings and errors as notifications/message
        return {{"protocolVersion", use},
                {"capabilities", caps},
                {"serverInfo", {{"name", "dayfall"}, {"title", "DAYFALL engine"}, {"version", "0.1.0"}}},
                {"instructions", editor_.instructions() +
                                     "\n\nMCP resources: the docs (dayfall://docs/agent-workflow, map-format, tools, porting), the live "
                                     "map document (dayfall://map/document; one section: dayfall://map/section/{section}) and the newest "
                                     "captures (dayfall://captures/{file}). Prompts: build_level, review_level, refine_area, test_route."}};
    }
    if (method == "ping") return json::object();
    if (method == "tools/list") return {{"tools", toolList()}};
    if (method == "tools/call") return callTool(id, params, s, notify, noResponse);
    if (method == "resources/list") return {{"resources", resourceList()}};
    if (method == "resources/templates/list") return {{"resourceTemplates", resourceTemplates()}};
    if (method == "resources/read") {
        if (!params.contains("uri") || !params["uri"].is_string()) throw RpcError(kInvalidParams, "resources/read needs a uri");
        return readResource(params["uri"].get<std::string>());
    }
    if (method == "prompts/list") return {{"prompts", promptList()}};
    if (method == "prompts/get") {
        if (!params.contains("name") || !params["name"].is_string()) throw RpcError(kInvalidParams, "prompts/get needs a prompt name");
        return getPrompt(params["name"].get<std::string>(), params.value("arguments", json::object()));
    }
    if (method == "logging/setLevel") {
        std::string level = params.value("level", "");
        auto it = std::find(std::begin(kLogLevels), std::end(kLogLevels), level);
        if (it == std::end(kLogLevels)) throw RpcError(kInvalidParams, "unknown log level '" + level + "'");
        s.logLevel = (int)(it - std::begin(kLogLevels));
        return json::object();
    }
    throw RpcError(kMethodNotFound, "method not found: " + method);
}

std::optional<json> McpServer::handleText(const std::string& text, McpSession& session, const McpNotify& notify) {
    json msg;
    try {
        msg = json::parse(text);
    } catch (const std::exception& e) {
        return rpcError(nullptr, -32700, std::string("parse error: ") + e.what());
    }
    return handle(msg, session, notify);
}

std::optional<json> McpServer::handle(const json& msg, McpSession& s, const McpNotify& notify) {
    if (msg.is_array()) {   // JSON-RPC batch (protocol revisions before 2025-06-18; still accepted)
        if (msg.empty()) return rpcError(nullptr, kInvalidRequest, "invalid request: empty batch");
        json out = json::array();
        for (auto& m : msg) if (auto r = handle(m, s, notify)) out.push_back(*r);
        if (out.empty()) return std::nullopt;
        return out;
    }
    if (!msg.is_object() || !msg.contains("method") || !msg["method"].is_string()) {
        if (msg.is_object() && (msg.contains("result") || msg.contains("error"))) return std::nullopt;   // a response to us: ignore
        return rpcError(msg.is_object() ? msg.value("id", json()) : json(), kInvalidRequest, "invalid request");
    }
    std::string method = msg["method"].get<std::string>();
    const json params = msg.contains("params") && msg["params"].is_object() ? msg["params"] : json::object();
    if (!msg.contains("id")) {   // notifications
        if (method == "notifications/initialized") s.initialized = true;
        else if (method == "notifications/cancelled" && params.contains("requestId")) cancel(s, params["requestId"]);
        return std::nullopt;
    }
    const json id = msg["id"];
    bool noResponse = false;
    try {
        json result = handleRequest(method, id, params, s, notify, noResponse);
        if (noResponse) return std::nullopt;
        return rpcResult(id, std::move(result));
    } catch (const RpcError& e) {
        return rpcError(id, e.code, e.what(), e.data);
    } catch (const json::exception& e) {
        return rpcError(id, kInvalidParams, std::string("invalid params: ") + e.what());
    } catch (const std::exception& e) {
        return rpcError(id, kInternalError, std::string("internal error: ") + e.what());
    }
}

// ------------------------------------------------------------------------------------- stdio
void StdioTransport::write(const json& msg) {
    std::string s = dumpJson(msg);
    std::lock_guard lock(out_);
    std::fwrite(s.data(), 1, s.size(), stdout);
    std::fputc('\n', stdout);
    std::fflush(stdout);
}

void StdioTransport::start(McpServer& server, std::atomic<bool>& quit) {
#ifndef _WIN32
    std::signal(SIGPIPE, SIG_IGN);   // a client that went away must not kill the editor
#endif
    setLogSink([this](LogLevel level, const std::string& msg) {
        int rank = level == LogLevel::Info ? 1 : level == LogLevel::Warn ? 3 : 4;
        if (!session_.initialized || rank < session_.logLevel) return;
        write({{"jsonrpc", "2.0"}, {"method", "notifications/message"}, {"params", {{"level", kLogLevels[rank]}, {"logger", "dayfall"}, {"data", msg}}}});
    });
    thread_ = std::thread([this, &server, &quit] {
        McpNotify notify = [this](const json& n) { write(n); };
        std::string line;
        while (std::getline(std::cin, line)) {
            if (!line.empty() && line.back() == '\r') line.pop_back();
            if (line.empty()) continue;
            json msg;
            try {
                msg = json::parse(line);
            } catch (const std::exception& e) {
                write(rpcError(nullptr, -32700, std::string("parse error: ") + e.what()));
                continue;
            }
            // requests run on their own threads so that a notifications/cancelled can arrive while a tool runs;
            // initialize, notifications and batches are handled here, in order
            bool async = msg.is_object() && msg.contains("id") && msg.contains("method") && msg["method"] != "initialize";
            if (!async) {
                if (auto r = server.handle(msg, session_, notify)) write(*r);
                continue;
            }
            {
                std::lock_guard lock(pendingMutex_);
                ++pending_;
            }
            std::thread([this, &server, notify, msg = std::move(msg)] {
                try {
                    if (auto r = server.handle(msg, session_, notify)) write(*r);
                } catch (const std::exception& e) {
                    logError("MCP: {}", e.what());
                }
                std::lock_guard lock(pendingMutex_);
                --pending_;
                pendingCv_.notify_all();
            }).detach();
        }
        {   // stdin closed: answer what is still running, then quit
            std::unique_lock lock(pendingMutex_);
            pendingCv_.wait(lock, [this] { return pending_ == 0; });
        }
        setLogSink(nullptr);
        logInfo("MCP stdin closed: shutting down");
        quit = true;
    });
}

void StdioTransport::stop() {
    if (thread_.joinable()) thread_.detach();   // blocked in getline; the process is exiting
}

// ------------------------------------------------------------------------------------- http
namespace {
#ifdef _WIN32
using Sock = SOCKET;
constexpr int kSendFlags = 0;
#else
using Sock = int;
constexpr int kSendFlags = MSG_NOSIGNAL;   // a closed connection is an error, not SIGPIPE
#endif
void closeSock(intptr_t s) {
#ifdef _WIN32
    closesocket((SOCKET)s);
#else
    ::close((int)s);
#endif
}
bool sendAll(intptr_t s, const std::string& data) {
    size_t off = 0;
    while (off < data.size()) {
        auto n = ::send((Sock)s, data.data() + off, (int)(data.size() - off), kSendFlags);
        if (n <= 0) return false;
        off += (size_t)n;
    }
    return true;
}
std::string lower(std::string s) { for (auto& c : s) c = (char)tolower((unsigned char)c); return s; }
// DNS-rebinding protection: browsers may only reach the editor from local pages
bool localOrigin(const std::string& origin) {
    std::string o = lower(origin);
    size_t p = o.find("://");
    if (p == std::string::npos) return false;
    std::string host = o.substr(p + 3);
    host = host.substr(0, host.find('/'));
    if (host.rfind("[::1]", 0) == 0) return host.size() == 5 || host[5] == ':';
    host = host.substr(0, host.find(':'));
    return host == "localhost" || host == "127.0.0.1";
}
}  // namespace

std::shared_ptr<McpSession> HttpTransport::session(const std::string& id) {
    std::lock_guard lock(sessionsMutex_);
    auto it = sessions_.find(id);
    return it == sessions_.end() ? nullptr : it->second;
}

std::shared_ptr<McpSession> HttpTransport::newSession(const std::string& protocol) {
    std::random_device rd;
    std::string id = std::format("{:08x}{:08x}{:08x}{:08x}", rd(), rd(), rd(), rd());
    auto s = std::make_shared<McpSession>(id, false, protocol);
    std::lock_guard lock(sessionsMutex_);
    sessions_[id] = s;
    sessionOrder_.push_back(id);
    while (sessionOrder_.size() > 256) {   // clients that never sent DELETE
        sessions_.erase(sessionOrder_.front());
        sessionOrder_.pop_front();
    }
    return s;
}

bool HttpTransport::start(McpServer& server, const std::string& host, int port) {
#ifdef _WIN32
    WSADATA wsa;
    WSAStartup(MAKEWORD(2, 2), &wsa);
#else
    std::signal(SIGPIPE, SIG_IGN);
#endif
    server_ = &server;
    sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_port = htons((uint16_t)port);
    if (inet_pton(AF_INET, host.c_str(), &addr.sin_addr) != 1 || (ntohl(addr.sin_addr.s_addr) >> 24) != 127) {
        logError("MCP http: {} is not a loopback address; the editor only serves this machine", host);
        return false;
    }
    auto s = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    int yes = 1;
    setsockopt(s, SOL_SOCKET, SO_REUSEADDR, (const char*)&yes, sizeof(yes));
    if (bind(s, (sockaddr*)&addr, sizeof(addr)) != 0 || listen(s, 8) != 0) {
        closeSock((intptr_t)s);
        logError("MCP http: cannot listen on {}:{} (in use?)", host, port);
        return false;
    }
    listen_ = (intptr_t)s;
    port_ = port;
    running_ = true;
    thread_ = std::thread([this] {
        while (running_) {
            sockaddr_in ca{};
            socklen_t len = sizeof(ca);
            auto c = accept((Sock)listen_, (sockaddr*)&ca, &len);
            if (!running_) break;
            if ((intptr_t)c < 0) continue;
            std::thread([this, c] { serve((intptr_t)c); }).detach();
        }
    });
    logInfo("MCP server listening on http://{}:{}/mcp", host, port);
    return true;
}

void HttpTransport::serve(intptr_t c) {
    {   // progress is written from the main thread: a client that stops reading must not stall it for long
        int one = 1;
#ifdef _WIN32
        DWORD timeout = 10000;
#else
        timeval timeout{10, 0};
#endif
        setsockopt((Sock)c, SOL_SOCKET, SO_SNDTIMEO, (const char*)&timeout, sizeof(timeout));
        setsockopt((Sock)c, IPPROTO_TCP, TCP_NODELAY, (const char*)&one, sizeof(one));
    }
    std::string buf;
    char tmp[65536];
    for (;;) {
        // headers
        size_t hdrEnd;
        while ((hdrEnd = buf.find("\r\n\r\n")) == std::string::npos) {
            auto n = recv((Sock)c, tmp, sizeof(tmp), 0);
            if (n <= 0) { closeSock(c); return; }
            buf.append(tmp, (size_t)n);
            if (buf.size() > (1u << 20)) {
                sendAll(c, "HTTP/1.1 431 Request Header Fields Too Large\r\nContent-Length: 0\r\nConnection: close\r\n\r\n");
                closeSock(c);
                return;
            }
        }
        std::istringstream hs(buf.substr(0, hdrEnd));
        std::string method, path, version, line;
        hs >> method >> path >> version;
        std::getline(hs, line);
        std::map<std::string, std::string> headers;
        while (std::getline(hs, line)) {
            if (!line.empty() && line.back() == '\r') line.pop_back();
            auto colon = line.find(':');
            if (colon == std::string::npos) continue;
            std::string v = line.substr(colon + 1);
            v.erase(0, v.find_first_not_of(' '));
            headers[lower(line.substr(0, colon))] = v;
        }
        auto header = [&](const char* k) { auto it = headers.find(k); return it == headers.end() ? std::string() : it->second; };
        bool close = lower(header("connection")) == "close";
        auto reply = [&](int code, const char* status, const char* type, const std::string& content, const std::string& extra = "") {
            std::string r = std::format("HTTP/1.1 {} {}\r\nContent-Type: {}\r\nContent-Length: {}\r\nConnection: {}\r\n{}\r\n", code, status,
                                        type, content.size(), close ? "close" : "keep-alive", extra);
            return sendAll(c, r + content);
        };
        auto replyError = [&](int code, const char* status, int rpcCode, const std::string& msg) {
            return reply(code, status, "application/json", dumpJson(rpcError(nullptr, rpcCode, msg)));
        };
        // body: Content-Length only, at most kMaxBody
        size_t length = 0;
        bool badLength = false;
        try {
            if (!header("content-length").empty()) length = std::stoull(header("content-length"));
        } catch (const std::exception&) {
            badLength = true;
        }
        if (badLength || !header("transfer-encoding").empty() || length > kMaxBody) {
            close = true;
            if (length > kMaxBody) replyError(413, "Payload Too Large", kInvalidRequest, std::format("request body over {} MB", kMaxBody >> 20));
            else if (badLength) replyError(400, "Bad Request", kInvalidRequest, "bad Content-Length");
            else replyError(411, "Length Required", kInvalidRequest, "send the body with Content-Length");
            closeSock(c);
            return;
        }
        while (buf.size() < hdrEnd + 4 + length) {
            auto n = recv((Sock)c, tmp, sizeof(tmp), 0);
            if (n <= 0) { closeSock(c); return; }
            buf.append(tmp, (size_t)n);
        }
        std::string body = buf.substr(hdrEnd + 4, length);
        buf.erase(0, hdrEnd + 4 + length);

        bool ok = true;
        if (!header("origin").empty() && !localOrigin(header("origin"))) {
            ok = reply(403, "Forbidden", "text/plain", "origin not allowed");
        } else if (path == "/mcp" || path.rfind("/mcp?", 0) == 0 || path.rfind("/mcp/", 0) == 0) {
            std::string sid = header("mcp-session-id"), pv = header("mcp-protocol-version");
            if (method == "POST") {
                json msg;
                bool parsed = true;
                try {
                    msg = json::parse(body);
                } catch (const std::exception& e) {
                    parsed = false;
                    ok = replyError(400, "Bad Request", -32700, std::string("parse error: ") + e.what());
                }
                bool init = parsed && msg.is_object() && msg.value("method", json()) == "initialize";
                std::shared_ptr<McpSession> s;
                if (!parsed) {   // answered above
                } else if (!pv.empty() && !McpServer::supportsProtocol(pv)) {
                    ok = replyError(400, "Bad Request", kInvalidRequest, "unsupported MCP-Protocol-Version: " + pv);
                } else if (init) {
                    s = newSession(pv.empty() ? McpServer::defaultProtocol() : pv);   // initialize negotiates the real one
                } else if (!sid.empty()) {
                    s = session(sid);
                    if (!s) ok = replyError(404, "Not Found", -32001, "unknown or expired session: initialize again");
                } else {   // no session: allowed for simple clients (curl), at the protocol they name
                    s = std::make_shared<McpSession>("", false, pv.empty() ? McpServer::defaultProtocol() : pv);
                }
                if (s) {
                    std::string sessionHeader = s->id.empty() ? "" : std::format("Mcp-Session-Id: {}\r\n", s->id);
                    // a tools/call that reports progress is answered as an event stream when the client takes one:
                    // the progress notifications, then the response. Started lazily, so everything else stays plain JSON.
                    bool sse = lower(header("accept")).find("text/event-stream") != std::string::npos;
                    std::mutex streamMutex;
                    bool streaming = false, broken = false;
                    auto chunk = [&](const std::string& data) { return sendAll(c, std::format("{:x}\r\n", data.size()) + data + "\r\n"); };
                    McpNotify notify = [&](const json& n) {
                        std::lock_guard lock(streamMutex);
                        if (broken) return;
                        if (!streaming) {
                            streaming = true;
                            broken = !sendAll(c, std::format("HTTP/1.1 200 OK\r\nContent-Type: text/event-stream\r\nCache-Control: no-cache\r\n"
                                                             "Transfer-Encoding: chunked\r\nConnection: {}\r\n{}\r\n",
                                                             close ? "close" : "keep-alive", sessionHeader));
                        }
                        if (!broken) broken = !chunk("event: message\ndata: " + dumpJson(n) + "\n\n");
                    };
                    auto resp = server_->handle(msg, *s, sse ? notify : McpNotify());
                    if (init && resp && resp->contains("error")) {
                        std::lock_guard lock(sessionsMutex_);
                        sessions_.erase(s->id);
                    }
                    std::lock_guard lock(streamMutex);
                    if (streaming) ok = !broken && (!resp || chunk("event: message\ndata: " + dumpJson(*resp) + "\n\n")) && sendAll(c, "0\r\n\r\n");
                    else if (resp) ok = reply(200, "OK", "application/json", dumpJson(*resp), sessionHeader);
                    else ok = reply(202, "Accepted", "text/plain", "", sessionHeader);   // notifications and responses only
                }
            } else if (method == "DELETE") {   // the client ends its session
                bool erased = false;
                if (!sid.empty()) {
                    std::lock_guard lock(sessionsMutex_);
                    erased = sessions_.erase(sid) > 0;
                    if (erased) sessionOrder_.erase(std::remove(sessionOrder_.begin(), sessionOrder_.end(), sid), sessionOrder_.end());
                }
                if (sid.empty()) ok = replyError(400, "Bad Request", kInvalidRequest, "DELETE needs the Mcp-Session-Id header");
                else if (!erased) ok = replyError(404, "Not Found", -32001, "unknown or expired session");
                else ok = reply(200, "OK", "text/plain", "");
            } else {
                ok = reply(405, "Method Not Allowed", "text/plain", "this server does not open SSE streams on GET; POST JSON-RPC to /mcp",
                           "Allow: POST, DELETE\r\n");
            }
        } else if (method == "GET" && path == "/") {
            ok = reply(200, "OK", "text/plain", std::format("DAYFALL engine MCP server\nPOST JSON-RPC to /mcp\ntool calls served: {}\n", server_->calls.load()));
        } else {
            ok = reply(404, "Not Found", "text/plain", "not found");
        }
        if (!ok || close) { closeSock(c); return; }
    }
}

void HttpTransport::stop() {
    if (!running_) return;
    running_ = false;
#ifndef _WIN32
    ::shutdown((int)listen_, SHUT_RDWR);
#endif
    closeSock(listen_);
    if (thread_.joinable()) thread_.join();
}
}  // namespace df
